import SwiftUI

struct ColorPreviewView: View {
    @Binding var color: Color

    var body: some View {
        RoundedRectangle(cornerRadius: 0)
            .foregroundColor(color)
            .overlay(
              RoundedRectangle(cornerRadius: 0)
                .stroke(Color.brown, lineWidth: 10)  /*.overlay(
                                                      RoundedRectangle(cornerRadius: 0)
                                                          .stroke(Color(red: max(0, redColor / 255 - 0.2), green: max(0, greenColor / 255 - 0.2), blue: max(0, blueColor / 255 - 0.2)), lineWidth: 5))*/
                                                    // this is to obtain a darker color than the one generated by the sliders (google...)
              )
    }
}
struct ColorSliderView: View {
  @Binding var colorValue: Double
  var label: String
  var accentColor: Color
  var body: some View {
    VStack {
      Text(label)
      HStack {
        Slider(value: $colorValue, in: 0...255)
          .accentColor(accentColor)
        Text("\(Int(colorValue.rounded()))")
      }
    }
  }
}
